name: Run Server

on:
  push:
    branches:
      - main

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 13.14.0

    - name: Install Dependencies
      run: npm install

    - name: Run Server
      run: node server.js
      
